# 
# Copyright 2018 Martin Goellnitz
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
image: gradle:4.7-jdk8

before_script:
  - export GRADLE_USER_HOME=/tmp/.gradle
  - wget -O l4j.tgz https://netix.dl.sourceforge.net/project/launch4j/launch4j-3/3.11/launch4j-3.11-linux-x64.tgz
  - tar xzf l4j.tgz
  - ls
  - export PATH=./launch4j:$PATH

stages:
  - JFileSync

build:
  stage: JFileSync
  script: gradle clean build
  artifacts:
    paths:
    - build/distributions/*
    expire_in: 30 days
    name: ${CI_BUILD_STAGE}

cache:
  paths:
  - /tmp/.gradle/caches/
  - /tmp/.gradle/wrapper/
